/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated.matches'
import { Route as AuthenticatedLadderRouteImport } from './routes/_authenticated.ladder'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated.challenges'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLadderRoute = AuthenticatedLadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ladder': typeof AuthenticatedLadderRoute
  '/matches': typeof AuthenticatedMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ladder': typeof AuthenticatedLadderRoute
  '/matches': typeof AuthenticatedMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ladder': typeof AuthenticatedLadderRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/admin'
    | '/challenges'
    | '/dashboard'
    | '/ladder'
    | '/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/admin'
    | '/challenges'
    | '/dashboard'
    | '/ladder'
    | '/matches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/_authenticated/admin'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/ladder'
    | '/_authenticated/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ladder': {
      id: '/_authenticated/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof AuthenticatedLadderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLadderRoute: typeof AuthenticatedLadderRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLadderRoute: AuthenticatedLadderRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
